server:
  port: 8080

spring:
  application:
    name: seata-order-service
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://119.29.151.146:3307/seata_order?serverTimezone=UTC
      username: root
      password: root
  cloud:
    nacos:
      discovery:
        server-addr: 119.29.151.146:8868
    alibaba:
      seata:
        # Seata 事务组名称，对应file.conf文件中 service中vgroup_mapping.xxx="default"
        tx-service-group: order-service-group

seata:
  service:
    grouplist:
      key: 119.29.151.146
      value: 8091

mybatis:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.zhihao.entity

# 开放监控管理路径
management:
  endpoints:
    web:
      exposure:
        include: '*'

ribbon:
  ConnectTimeout: 30000 # Ribbon请求连接的超时时间，默认值2000
  ReadTimeout: 30000 # 读取超时时间，默认值5000
