server:
  port: 8080

spring:
  application:
    name: seata-order-service
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-bp1dfedzn548193uedo.mysql.rds.aliyuncs.com:3306/seata_order?serverTimezone=UTC
      username: ymt
      password: YMTNSN@ssw0rd
  cloud:
    nacos:
      discovery:
        server-addr: nacos-dev.hpcang.com:80
    alibaba:
      seata:
        # Seata 事务组名称，对应file.conf文件中 service中vgroup_mapping.xxx="default"
        tx-service-group: order-service-group


#seata:
#  service:
#    grouplist:
#      key: 192.168.13.40
#      value: 8091

mybatis:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.zhihao.entity

# 开放监控管理路径
management:
  endpoints:
    web:
      exposure:
        include: '*'

ribbon:
  ConnectTimeout: 30000 # Ribbon请求连接的超时时间，默认值2000
  ReadTimeout: 30000 # 读取超时时间，默认值5000

seata:
  enabled: true
  application-id: order-service
  tx-service-group: order-service-group
  enable-auto-data-source-proxy: true
  data-source-proxy-mode: AT
  use-jdk-proxy: false
  excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
  client:
    rm:
      async-commit-buffer-limit: 1000
      report-retry-count: 5
      table-meta-check-enable: false
      report-success-enable: false
      saga-branch-register-enable: false
      saga-json-parser: fastjson
      lock:
        retry-interval: 10
        retry-times: 30
        retry-policy-branch-rollback-on-conflict: true
    tm:
      commit-retry-count: 5
      rollback-retry-count: 5
      default-global-transaction-timeout: 60000
      degrade-check: false
      degrade-check-period: 2000
      degrade-check-allow-times: 10
    undo:
      data-validation: true
      log-serialization: jackson
      log-table: undo_log
      only-care-update-columns: true
    log:
      exceptionRate: 100
  service:
    vgroup-mapping:
      order-service-group: default
    grouplist:
      default: 192.168.14.164:8091
    enable-degrade: false
    disable-global-transaction: false
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
      worker-thread-size: default
      boss-thread-size: 1
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true

  registry:
    type: redis
    load-balance: RandomLoadBalance
    load-balance-virtual-nodes: 10

    redis:
      server-addr: app-redis-01-sh-dev.redis.rds.aliyuncs.com:6379
      db: 0
      password: HpcDevRedis#2020#
      timeout: 0
      cluster: "default"